FishesOnRails/config/routes.rb
Rails.application.routes.draw do
	
  
  root 'static_pages#home', as: "home"
  
  
  get '/login', to: 'users#login' , as: "login"
  post 'users/login', to: 'users#new' 
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about' , as: "about"
  get '/about_me', to: 'static_pages#about_me', as: "nous"
  get '/about_my_group', to: 'static_pages#about_my_group', as: "atlantide"
  get '/users/:username', to: 'users#profil' , as: 'user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

FishesOnRails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

FishesOnRails/app/models/user.rb
class User < ApplicationRecord

	validates :username, uniqueness: true,
						presence: true,
						format: { with: /\A[a-zA-Z0-9]+\Z/ }
 
end
 

FishesOnRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

FishesOnRails/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
  def about_me
  end

  def about_my_group
  end

  def about
  end

  def home
  end

  def contact
  end

  def new_user
  end

end

FishesOnRails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
  	@user = User.new
  end
  
 def new

    @user = User.new(username: params["username"] ,bio: params["bio"])
    if @user.save
    	redirect_to user_path(@user.username)  
    else
    	render 'login'
    end
 end
  
  def profil
  
  @user = User.find_by_username(params[:username])
  end 


end

FishesOnRails/app/helpers/application_helper.rb
module ApplicationHelper
end

FishesOnRails/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

FishesOnRails/app/helpers/user_helper.rb
module UserHelper
end

FishesOnRails/app/helpers/users_helper.rb
module UsersHelper
end

FishesOnRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AbdelOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div><%= flash[:info] %></div>
    <%= yield %>
  </body>
</html>

FishesOnRails/app/views/static_pages/about.html.erb
<h1>A Propos</h1><br>
<%= link_to "A propos de nous", nous_path%><br>
<%= link_to "A propos de notre groupe", atlantide_path%> <br><br>
<%= link_to "retour accueil", home_path%><br>

FishesOnRails/app/views/static_pages/about_me.html.erb
<h1>A propos de nous </h1> <br>
<p>Selma: Jeune demoiselle recherche un mec mortel</p><br>
<p>Abdel: Futur dev inchallah </p>
<%= link_to "retour accueil", home_path%><br>

FishesOnRails/app/views/static_pages/about_my_group.html.erb
<h1>A propos du groupe</h1><br>
<p>équipe Atlantide dans la place </p>
<ul>
<li>Quentin Berson</li>
<li>Alexandra Dlg</li>
<li>Abdel Ait Bali</li>
<li>Selma Kabous</li>
</ul>

<%= link_to "retour accueil", home_path%><br>

FishesOnRails/app/views/static_pages/contact.html.erb
<h1>CONTACT</h1>

<%= link_to "retour accueil", home_path%><br>

FishesOnRails/app/views/static_pages/home.html.erb
<h1> Accueil</h1>
<p>Bienvenus sur notre page d accueil</p><br>
<%= link_to "A propos", about_path%><br><br><br><br>

<%= link_to "Créer votre compte", login_path%><br>

FishesOnRails/app/views/users/login.html.erb
<h1>Connexion</h1>


<%= link_to "retour accueil", home_path%><br>
    <% if @user.errors.any? %>
        <div>
            <% pluralize(@user.errors.count, "Error") %> 
            <p class ="errors" >This username can't be registered : </p>
            <ul class ="errors">
                <% @user.errors.full_messages.each do |msg| %>
                    <% if msg == "Username is invalid" %>
                        <li> <%= "Your Name can't contains whitespaces or special characters" %> </li>
                    <% else %> 
                    <li><%= msg %></li>
                    <% end %>
                <% end %>
            </ul>
        </div>
    <% end %> 

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<%= form_tag "/users/login", method: :post do %><br><br><br>
    <p>Renseignez votre nom</p>
  <input type="text" name="username" /><br><br><br>

  <p>Renseignez votre biograhie</p>
  <textarea type="text" name="bio" ></textarea><br><br><br>
  <input type="submit" value="Se connecter" />

<% end %>

FishesOnRails/app/views/users/profil.html.erb
<h1>Bienvenue <%= @user.username %></h1><br>

<h2>Votre bio </h2>
<p><%= @user.bio %></p>